app/models/battle.py
class Battle:
    def __init__(self, datos_pokemon_jugador, datos_pokemon_rival, vida_jugador, vida_rival, ataques_jugador, ataques_rival):
        self.turno = 1
        self.datos_pokemon_jugador = datos_pokemon_jugador
        self.datos_pokemon_rival = datos_pokemon_rival
        self.log = []
        self.vida_jugador = vida_jugador
        self.vida_rival = vida_rival
        self.ataques_jugador = ataques_jugador
        self.ataques_rival = ataques_rival

app/routes/battle_routes.py
from flask import Blueprint, redirect, render_template, request, session, url_for

from app.forms.pokemon_select_form import PokemonSelectForm
from app.services import pokemon_service
from app.services.pokemon_service import obtener_pokemon_por_nombre_cliente
from app.services.current_year_service import get_current_year
from app.services.battle_service import random_atacar, atacar_turno, inicializar_batalla, elegir_rival_aleatorio, insertar_batalla_base
from app.models.exceptions import BatallaIncompletaException, EntrenadorNotFoundException, NoHayEntrenadoresException

current_year = get_current_year()
battle_bp = Blueprint('battle', __name__)


@battle_bp.route("/")
def battle():
    pokemon_name = session.get("pokemon_elegido")
    entrenador = session.get("entrenador")

    # Si intenta acceder directamente por la url sin haber elegido pokemon o entrenador, lo redirigimos
    if not pokemon_name or not entrenador:
        return redirect(url_for("pokemon.lista"))

    # Obtenemos el pokemon
    pokemon_elegido = obtener_pokemon_por_nombre_cliente(pokemon_name)

    # Por si a pesar de validar en lista consiguen llegar aquí
    if not pokemon_elegido:
        return redirect(url_for("pokemon.lista"))

    # Si no hay pokemon rival, lo generamos
    if not session.get("entrenador_rival"):
        try:
            entrenador_rival = elegir_rival_aleatorio(entrenador)

            session["entrenador_rival"] = entrenador_rival.nombre
            session["entrenador_rival_id"] = entrenador_rival.id
        except NoHayEntrenadoresException:
            return redirect(url_for("pokemon.lista"))

    # Creamos una nueva batalla si no lo habíamos hecho
    if not session.get("battle"):
        try:
            battle = inicializar_batalla(pokemon_elegido)
            session["battle"] = battle.__dict__
        except Exception:
            return redirect(url_for("pokemon.lista"))

    return render_template("battle.html", year=current_year)


@battle_bp.route("/ataque", methods=["GET", "POST"])
def atacar():
    # GET (venimos directamente por la url)
    if request.method == "GET":
        return redirect(url_for("battle.battle"))

    # POST (seleccionamos ataque en battle)
    # Obtenemos el pokemon para acceder a sus ataques
    pokemon_name = session.get("pokemon_elegido")
    pokemon = obtener_pokemon_por_nombre_cliente(pokemon_name)

    if not pokemon:
        return redirect(url_for("pokemon.lista"))

    ataque_name = request.form.get("ataque_name")
    battle_object = session.get("battle")

    for ataque in pokemon["moves"]:
        if ataque["name"] == ataque_name:
            # TURNO JUGADOR
            acabar_batalla, battle_object_service = atacar_turno(damage=ataque["power"],
                                                                 accuracy=ataque["accuracy"],
                                                                 battle_object=battle_object,
                                                                 pokemon_name=pokemon_name,
                                                                 ataque_name=ataque_name,
                                                                 # para controlar si el personaje que ataca es el jugador en el service
                                                                 atacante_jugador=True)

            session["battle"] = battle_object_service

            # Si el pokemon tiene 0 de vida, acabamos
            if acabar_batalla:
                try:
                    batalla_sesion = session.get("battle")

                    pokemon_jugador = batalla_sesion["datos_pokemon_jugador"]["name"]
                    pokemon_rival = batalla_sesion["datos_pokemon_rival"]["name"]
                    id_ganador = session.get("entrenador_id")
                    id_perdedor = session.get("entrenador_rival_id")

                    insertar_batalla_base(
                        id_ganador=id_ganador, pokemon_atacante=pokemon_jugador, pokemon_defensor=pokemon_rival, id_perdedor=id_perdedor)

                except BatallaIncompletaException or EntrenadorNotFoundException:
                    return redirect("pokemon.lista")

                return redirect(url_for("battle.resultado"))

            # TURNO RIVAL
            ataque_rival = random_atacar(
                battle_object.get("ataques_rival"))

            acabar_batalla, battle_object_service = atacar_turno(damage=ataque_rival["power"],
                                                                 accuracy=ataque_rival["accuracy"],
                                                                 battle_object=battle_object,
                                                                 pokemon_name=pokemon_name,
                                                                 ataque_name=ataque_rival["name"],
                                                                 atacante_jugador=False)

            session["battle"] = battle_object_service

            # Si el pokemon tiene 0 de vida, acabamos
            if acabar_batalla:
                try:
                    batalla_sesion = session.get("battle")

                    pokemon_jugador = batalla_sesion["datos_pokemon_jugador"]["name"]
                    pokemon_rival = batalla_sesion["datos_pokemon_rival"]["name"]
                    id_ganador = session.get("entrenador_rival_id")
                    id_perdedor = session.get("entrenador_id")

                    insertar_batalla_base(
                        id_ganador=id_ganador, pokemon_atacante=pokemon_jugador, pokemon_defensor=pokemon_rival, id_perdedor=id_perdedor)

                    # batalla = insertar_batalla_base()

                except BatallaIncompletaException:
                    return redirect("pokemon.lista")

                return redirect(url_for("battle.resultado"))

            return redirect(url_for("battle.battle"))

    return redirect(url_for("pokemon.lista"))


@battle_bp.route("/resultado")
def resultado():
    # Obtenemos los datos antes de quitarlos de la sesión
    battle_object = session.get("battle")
    pokemon_name = session.get("pokemon_elegido")

    if not battle_object or not pokemon_name:
        return redirect(url_for("pokemon.lista"))

    session.pop("battle")
    session.pop("pokemon_elegido")
    session.pop("entrenador_rival")

    return render_template("resultado.html", year=current_year, battle=battle_object)

app/routes/entrenador_routes.py
from flask import Blueprint, redirect, render_template, session, url_for

from app.models.exceptions import EntrenadorNotFoundException
from app.services.battle_service import obtener_todas_batallas_id_entrenador
from app.services.current_year_service import get_current_year


entrenador_bp = Blueprint("entrenador", __name__)


@entrenador_bp.route("/historial-batallas")
def historial_batallas():
    id_entrenador = session.get("entrenador_id")

    try:
        batallas = obtener_todas_batallas_id_entrenador(id_entrenador)
    except EntrenadorNotFoundException:
        return redirect(url_for("home.index"))

    return render_template("historial_batallas.html", batallas=batallas, year=get_current_year())

app/routes/home_routes.py
from flask import Blueprint, jsonify, redirect, render_template, session, url_for

from app.models.exceptions import EntrenadorExistenteException, EntrenadorNoCreadoException, EntrenadorNotFoundException, ContraseñaIncorrectaException
from app.services.pokemon_service import listar_pokemon
from app.services.current_year_service import get_current_year
from app.forms.trainer_login_form import TrainerLoginForm
from app.forms.trainer_register_form import TrainerRegisterForm
from app.services.entrenador_service import autenticar_entrenador, registrar_entrenador

home_bp = Blueprint('home', __name__)

year = get_current_year()


@home_bp.route("/")
def index():
    return render_template("index.html", year=year)


@home_bp.route("/data")
def data():
    pokemons = listar_pokemon()
    # Pasamos los datos a diccionario, porque no podemos serializar a json objetos en python
    return jsonify([p.to_dict() for p in pokemons])


@home_bp.route("/login", methods=["GET", "POST"])
def login():
    form = TrainerLoginForm()

    # POST (venimos de introducir entrenador)
    if form.validate_on_submit():
        entrenador = form.entrenador.data
        contraseña = form.contraseña.data
        id_antigua = session.get("entrenador_id")

        try:
            entrenador_existe = autenticar_entrenador(entrenador, contraseña)
        except ContraseñaIncorrectaException:
            form.form_errors.append("Contraseña incorrecta")

            return render_template("formulario_login.html", form=form, year=year)

        except EntrenadorNotFoundException:
            form.form_errors.append("Credenciales incorrectas")

            return render_template("formulario_login.html", form=form, year=year)

        # Si inicia sesión en la misma cuenta, no reiniciamos la batalla ni nada
        if id_antigua == entrenador_existe.id:
            return redirect(url_for("pokemon.lista"))

        session["entrenador"] = entrenador_existe.nombre
        session["entrenador_id"] = entrenador_existe.id

        pokemon = session.get("pokemon_elegido")

        if session.get("battle"):
            session.pop("pokemon_elegido")
            session.pop("battle")

        # Si elegimos otro usuario reiniciamos el rival
        if session.get("entrenador_rival"):
            session.pop("entrenador_rival")

        if entrenador and pokemon:
            return redirect(url_for("battle.battle"))

        return redirect(url_for("pokemon.lista"))

    # GET
    return render_template("formulario_login.html", year=year, form=form)


@home_bp.route("/register", methods=["GET", "POST"])
def register():
    form = TrainerRegisterForm()

    # POST (venimos de introducir entrenador)
    if form.validate_on_submit():
        entrenador = form.entrenador.data
        contraseña = form.contraseña.data

        # Devuelve el entreandor si lo ha creado bien
        try:
            entrenador_creado = registrar_entrenador(entrenador, contraseña)

        except EntrenadorNoCreadoException:
            form.form_errors.append("Error al insertar los datos")

            return render_template("formulario_register.html", year=year, form=form)

        except EntrenadorExistenteException:
            form.form_errors.append(f"El usuario {entrenador} ya existe")

            return render_template("formulario_register.html", year=year, form=form)

        session["entrenador"] = entrenador_creado.nombre
        session["entrenador_id"] = entrenador_creado.id

        # Si teníamos una batalla en curso y nos registramos, eliminamos la batalla y el pokemon que había elegido
        if session.get("battle"):
            session.pop("battle")
            session.pop("pokemon_elegido")

        if session.get("entrenador_rival"):
            session.pop("entrenador_rival")

        # Si venimos de la lista y elegimos pokemon, lo llevmaos a la batalla directamente
        if session.get("pokemon_elegido"):
            return redirect(url_for("battle.battle"))

        return redirect(url_for("pokemon.lista"))

    # GET
    return render_template("formulario_register.html", year=year, form=form)


@home_bp.route("/logout")
def logout():
    if session.get("entrenador"):
        session.clear()

    return redirect(url_for("home.index"))

app/routes/pokemon_routes.py
from flask import Blueprint, abort, redirect, render_template, request, session, url_for

from app.services import pokemon_service
from app.services.current_year_service import get_current_year
from app.forms.pokemon_select_form import PokemonSelectForm
from app.models.exceptions import NoHayDataException


current_year = get_current_year()
pokemon_bp = Blueprint('pokemon', __name__)


@pokemon_bp.route("/", methods=["GET", "POST"])
def lista():
    page = request.args.get("pagina")

    try:
        if not page or int(page) < 1:
            page = 1
        else:
            page = int(page)
    except Exception:
        page = 1

    form = PokemonSelectForm()

    # POST (formulario seleccionar)
    if form.validate_on_submit():
        entrenador = session.get("entrenador")
        pokemon_name = form.pokemon.data

        try:
            pokemon_service.obtener_pokemon_por_nombre_cliente(
                pokemon_name)
        except NoHayDataException:
            form.pokemon.errors.append(
                f"El pokemon '{pokemon_name}' no existe. Elige uno válido")
            # Para que no se quede el valor introducido en el input
            form.pokemon.data = ""

            data = pokemon_service.obtener_pokemon_adaptado2(page)

            return render_template("lista_pokemon.html", pokemons=data["pokemons_adaptados"], form=form, year=current_year, pagina_actual=data["pagina"], previous=data["previous"], next=data["next"])

        session["pokemon_elegido"] = pokemon_name

        if not entrenador:
            return redirect(url_for("home.login"))

        # Si pasamos las validaciones anteriores, vamos a la batalla
        return redirect(url_for("battle.battle"))

    # GET (cargamos la lista directamente o venimos de elegir entrenador)
    data = pokemon_service.obtener_pokemon_adaptado2(page)

    return render_template("lista_pokemon.html", pokemons=data["pokemons_adaptados"], year=current_year, form=form, pagina_actual=data["pagina"], previous=data["previous"], next=data["next"])


@pokemon_bp.route("/<int:id>")
def pokemon_detalles(id):
    try:
        pokemon = pokemon_service.obtener_pokemon_por_id_client(id)
    except NoHayDataException:
        abort(404)

    return render_template("pokemon_detallado.html", pokemon_recibir=pokemon, year=current_year)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Cambiar título para cada página aquí -->
    <title>{% block title %}PokeWarriors{% endblock %}</title>
    <link rel="shortcut icon" href="{{url_for('static', filename='media/img/pokeball.ico')}}" type="image/x-icon">
    <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
    <!-- Importar fuente -->
    <link rel="stylesheet" href="{{url_for('static', filename = 'css/index-animations.css')}}">
    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" />

    <!-- Linkear css aquí -->
    {% block link %}

    {% endblock %}

</head>

<!-- Bloque para añadir clases a body (principalmente para el background) -->

<body class="relative min-h-screen {% block body_class %}{% endblock %}">
    <header class="fixed p-[1rem_2rem] w-screen">
        <nav>
            {% if session.entrenador %}
            <div class="flex items-center justify-between gap-4">
                <div class="flex items-center justify-center gap-3">
                    <div
                        class="flex items-center justify-center gap-2 flex-wrap px-3 py-1 bg-opacity-20 rounded-full shadow-sm {{bg_color_entrenador | default('bg-indigo-100')}}">
                        <span class="material-symbols-outlined text-indigo-800">
                            person
                        </span>
                        <p class="font-semibold">{{session.entrenador}}</p>
                    </div>

                    <a href="{{url_for('home.logout')}}"
                        class="flex justify-center items-center text-sm font-semibold transition-colors duration-100 hover:text-red-500 {{logout_text_color | default('text-blue-600')}}">
                        <span class="material-symbols-outlined">
                            logout
                        </span>
                        <p>Cerrar sesión</p>
                    </a>
                </div>
                {% endif %}

                <ul class="flex justify-end items-center gap-5 font-bold {{ nav_text_color | default('text-white') }}">
                    <li class="relative group p-1 hover:scale-105">
                        <a href="{{url_for('home.index')}}"
                            class="{{ nav_link_class | default('hover:text-yellow-400 transition-all duration-300') }}">
                            Inicio
                        </a>
                        <span
                            class="absolute left-0 -bottom-1 w-0 h-0.5 {{ nav_underline_color | default('bg-yellow-400') }} transition-all duration-300 group-hover:w-full"></span>
                    </li>

                    <li class="relative group p-1 hover:scale-105">
                        <a href="{{url_for('pokemon.lista')}}"
                            class="{{ nav_link_class | default('hover:text-yellow-400 transition duration-300') }}">
                            Pokemons
                        </a>
                        <span
                            class="absolute left-0 -bottom-1 w-0 h-0.5 {{ nav_underline_color | default('bg-yellow-400') }} transition-all duration-300 group-hover:w-full"></span>
                    </li>
                    {% if session.entrenador_id %}
                    <li class="relative group p-1 hover:scale-105">
                        <a href="{{url_for('entrenador.historial_batallas')}}"
                            class="{{ nav_link_class | default('hover:text-yellow-400 transition-all duration-300') }}">
                            Batallas
                        </a>
                        <span
                            class="absolute left-0 -bottom-1 w-0 h-0.5 {{ nav_underline_color | default('bg-yellow-400') }} transition-all duration-300 group-hover:w-full"></span>
                    </li>
                    {% endif %}

                    <li class="p-1 hover:scale-105">
                        <a href="{{url_for('home.login')}}"
                            class="{{ play_button_class | default('bg-green-500 rounded py-2 px-4 hover:bg-green-700 italic font-bold transition-all duration-300 ease-in-out') }}">
                            Jugar
                        </a>
                    </li>
                </ul>
        </nav>
    </header>

    <main class="pt-20 pb-10 aparecer">
        {% block main %}
        <!-- Insertar contenido principal aquí -->
        {% endblock %}

    </main>

    <footer
        class="absolute bottom-0 bg-transparent text-center text-{{ footer_text_color | default('white') }} w-full font-bold">
        <p>{{year}} - POKEWARRIORS® - TODOS LOS DERECHOS RESERVADOS</p>
    </footer>
</body>

</html>

app/templates/battle.html
{% extends "base.html" %}

{% block title %}PokeWarriors - Battle{% endblock %}

{% block link %}
<link rel="stylesheet" href="{{  url_for('static', filename = 'css/battle.css')}}">
{% endblock %}

{% set nav_text_color = "text-indigo-800 drop-shadow-sm" %}
{% set nav_link_class = "hover:text-yellow-500 transition-all duration-300" %}
{% set nav_underline_color = "bg-yellow-500" %}
{% set play_button_class = "bg-indigo-600 text-white rounded py-2 px-4 hover:bg-indigo-800 italic font-bold shadow-md
transition-all duration-300 ease-in-out" %}
{% set footer_text_color = "indigo-800" %}

{% block main %}
<section class="battle-screen">

    <!-- Entrenador Rival -->
    <div class="rival-trainer">
        <img src="{{url_for('static', filename='media/img/team_rocket.webp')}}" alt="Entrenador rival">
        <p>{{ session.get("entrenador_rival") }}</p>

    </div>

    <!-- Pokémon Rival -->
    <div class="rival-area">
        <div class="rival-info">
            <h3>{{session.battle.datos_pokemon_rival.name.upper()}}</h3>

            <div class="hp-bar">
                {% for hp in session.battle.datos_pokemon_rival.stats %}
                {% if hp.name == "hp" %}
                <progress value="{{session.battle.vida_rival*1/hp.value}}"></progress>
                <p>{{hp.name | capitalize}}: {{session.battle.vida_rival}}</p>
                {% endif%}
                {% endfor %}
            </div>

        </div>
        <img src="{{session.battle.datos_pokemon_rival.sprites.front_default}}"
            alt="{{session.battle.datos_pokemon_rival.sprites}}">
    </div>

    <!-- Pokémon Jugador -->
    <div class="player-area">
        <img src="{{session.battle.datos_pokemon_jugador.sprites.back_default}}"
            alt="{{session.battle.datos_pokemon_jugador.sprites}}">
        <div class="player-info">
            <h3>{{session.battle.datos_pokemon_jugador.name.upper()}}</h3>

            <div class="hp-bar">
                {% for hp in session.battle.datos_pokemon_jugador.stats %}
                {% if hp.name == "hp" %}
                <progress value="{{session.battle.vida_jugador*1/hp.value}}"></progress>
                <p>{{hp.name | capitalize}}: {{session.battle.vida_jugador}}</p>
                {% endif%}
                {% endfor %}
            </div>


        </div>
    </div>

    <!-- Entrenador Jugador -->
    <div class="player-trainer">
        <img src="{{url_for('static', filename='media/img/entrenador_ash.webp')}}" alt="Entrenador jugador">
        <p>{{session.entrenador}}</p>
    </div>

    <!-- Cuadro de opciones -->
    <div class="battle-options">
        <div class="battle-text">
            <p>¿Qué hará {{session.battle.datos_pokemon_jugador.name | capitalize}}?</p>
        </div>
        <div class="options-grid">
            {% for movimiento in session.battle.ataques_jugador %}
            <form action="{{url_for('battle.atacar')}}" method="post">
                <button class="fight" name="ataque_name" type="submit" value="{{movimiento.name}}">
                    Name:{{movimiento.name.upper()}}<br>
                    Power: {{movimiento.power * 0.20}}<br>
                    {% if not movimiento.accuracy%}
                    Accuracy: 100
                    {% else %}
                    Accuracy:{{movimiento.accuracy}}
                    {% endif %}
                </button>
            </form>
            {% endfor%}
        </div>
    </div>
</section>

<section class="container-log">
    <h1>Transcurso de la Batalla</h1>

    <div class="log">

        {% for log in session.battle.log%}
        <p>{{log}}</p>
        {% endfor%}
    </div>
</section>
{% endblock %}

app/templates/bienvenida.html
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pokemon battle web</title>
</head>

<body>
    <h1>BATALLAS POKEMON</h1>
    <footer>Batallas pokemon • Daniel • Francisco • 2025 - 2026</footer>
</body>

</html>

app/templates/formulario.html
{% extends "base.html" %}

{% block title%} PokeWarriors - Entrenador {% endblock %}


{% block body_class %}bg-[url('{{ url_for('static', filename='media/img/fondo-bienvenida.jpeg') }}')] bg-cover
bg-no-repeat{% endblock %}

{% set bg_color_entrenador = "bg-indigo-300"%}
{% set logout_text_color = "text-cyan-200"%}

{% block link %}
<link rel="stylesheet" href="{{  url_for('static', filename = 'css/formulario.css')}}">
{% endblock %}

{% block main %}
<section>
    <form action="" method="post">
        {{form.hidden_tag()}}

        {{form.entrenador.label(title="entrenador")}}
        <div class="icon-item-container">
            <span class="material-symbols-outlined">
                person
            </span>
            {{form.entrenador()}}
        </div>
        {{form.enviar()}}
        <div class="errores-container">
            {% for error in form.entrenador.errors%}
            <div class="error">{{error}}</div>
            {% endfor %}
        </div>
    </form>
</section>


{% endblock %}

app/templates/formulario_login.html
{% extends "base.html" %}

{% block title%} PokeWarriors - Login {% endblock %}


{% block body_class %}bg-[url('{{ url_for('static', filename='media/img/fondo-bienvenida.jpeg') }}')] bg-cover
bg-no-repeat{% endblock %}

{% set bg_color_entrenador = "bg-indigo-300"%}
{% set logout_text_color = "text-cyan-200"%}

{% block link %}
<link rel="stylesheet" href="{{  url_for('static', filename = 'css/auth.css')}}">
{% endblock %}

{% block main %}
<section class="flex flex-col gap-8">
    <h1 class="text-white text-4xl font-semibold">LOGIN</h1>
    <form action="" method="post">
        {{form.hidden_tag()}}

        {{form.entrenador.label(title="entrenador")}}
        <div class="icon-item-container">
            <span class="material-symbols-outlined">
                person
            </span>
            {{form.entrenador()}}
        </div>

        {{form.contraseña.label(title="contraseña")}}
        <div class="icon-item-container">
            <span class="material-symbols-outlined">
                key
            </span>
            {{form.contraseña()}}
        </div>

        {{form.enviar()}}

        <p>¿No tienes una cuenta? Créala <a href="{{ url_for('home.register') }}"
                class="underline text-blue-200 font-semibold">aquí</a></p>

        {% if form.errors %}

        {% set primer_error_clave = form.errors.keys() | list | first %}
        {% set primer_error = form.errors[primer_error_clave][0] %}

        <div class="errores-container">
            <div class="error">{{ primer_error }}</div>
        </div>
        {% endif %}
    </form>
</section>


{% endblock %}

app/templates/lista_pokemon.html
{% extends "base.html" %}

{% block title %} PokeWarriors - List {% endblock %}

{% block link %}
<link rel="stylesheet" href="{{  url_for('static', filename = 'css/pokemon-lista.css')}}">
<script src="{{url_for('static', filename = 'js/buscador-lista.js')}}" defer></script>
{% endblock %}

<!-- Variables base para que resalte la navbar -->

{% set nav_text_color = "text-indigo-800 drop-shadow-sm" %}
{% set nav_link_class = "hover:text-yellow-500 transition-all duration-300" %}
{% set nav_underline_color = "bg-yellow-500" %}
{% set play_button_class = "bg-indigo-600 text-white rounded py-2 px-4 hover:bg-indigo-800 italic font-bold shadow-md
transition-all duration-300 ease-in-out" %}
{% set footer_text_color = "indigo-800" %}


{% block main %}

<div class="flex justify-around items-center mb-10">
    <div>
        {% if previous %}
        <a href="{{ url_for('pokemon.lista', pagina=pagina_actual - 1) }}" class="text-white bg-blue-700 hover:bg-blue-800 hover:cursor-pointer focus:ring-4 
        focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2">Página anterior</a>
        {% endif %}
    </div>

    <p>Página actual: {{ pagina_actual }}</p>

    <div>
        {% if next %}
        <a href="{{ url_for('pokemon.lista', pagina=pagina_actual + 1) }}"
            class="text-white bg-blue-700 hover:bg-blue-800 hover:cursor-pointer focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2">Página
            siguiente</a>

        {% endif %}
    </div>
</div>

<form action="" method="post" class="max-w-md mx-auto mb-4 mt-4">
    {{form.hidden_tag()}}

    <label for="default-search" class="mb-2 text-sm font-medium text-gray-900 sr-only">Search</label>
    <div class="relative">
        <div class="absolute inset-y-0 start-0 flex items-center ps-3 pointer-events-none">
            <svg class="w-4 h-4 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg"
                fill="none" viewBox="0 0 20 20">
                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                    d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z" />
            </svg>
        </div>
        {{form.pokemon()}}
        {{form.enviar()}}
    </div>
</form>

<div class="flex flex-col">
    {% for error in form.pokemon.errors%}
    <div class="text-center text-red-500 font-bold">
        {{error}}
    </div>
    {% endfor %}
</div>

<div class="pokemon-container">
    {% for pokemon in pokemons %}
    <a href="{{ url_for('pokemon.pokemon_detalles', id = pokemon.id) }}">
        <div class="pokemon-card">
            <div class="title-img-container">
                <h3>{{pokemon.name}}</h3>

                <section class="img-iconos-container">
                    {% for tipo in pokemon.types%}
                    <img src="{{url_for('static', filename='media/img/tipos-pokemon/' + tipo + '.webp')}}"
                        alt="Tipo de pokemon" class="img-tipo">
                    {% endfor %}
                </section>
            </div>

            <img src="{{pokemon.sprites.front_default}}" alt="{{pokemon.sprites}}">

            {% for elemento in pokemon.types %}
            <p class="tipo-{{ elemento }}">{{ elemento }}</p>
            {% endfor %}

        </div>
    </a>
    {% endfor %}
</div>

{% endblock %}